version: 2
jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: test_mysql
          - DB_DATABASE: test
          - DB_USERNAME: root
          
          
      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: test
 
    steps:
      - checkout
 
      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql
 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
 
      - run: composer install -n --prefer-dist
 
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
            
      # - run: php artisan migrate
 
      # - run: ./vendor/bin/phpunit
      
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          SHA256:
            - "BnSV1mne+RngDW81EUqA5QxPd8N1LvC4fm6NxIolxQg"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /usr/share/nginx/html/'
      
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


